# Generated by Django 3.2.4 on 2021-06-22 08:40

from django.db import migrations, models
import students.validators


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_graduate_date2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=120, null=True, validators=[students.validators.email_stop_list_validator]),
        ),
    ]
