# Generated by Django 3.2.4 on 2021-06-11 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=80)),
                ('first_name', models.CharField(max_length=50)),
                ('birthdate', models.DateField(default=datetime.date.today)),
                ('email', models.EmailField(max_length=120, null=True)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('academic_subject', models.CharField(max_length=80)),
                ('academic_title', models.CharField(max_length=80)),
            ],
        ),
    ]
