# Generated by Django 3.2.4 on 2021-06-12 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_rename_teachers_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='academic_subject',
            new_name='academic_degrees',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='academic_title',
        ),
    ]
