# Generated by Django 3.2.4 on 2021-06-22 08:40

from django.db import migrations, models
import students.validators


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20210613_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=120, null=True, validators=[students.validators.email_stop_list_validator]),
        ),
    ]
