# Generated by Django 3.2.4 on 2021-06-11 05:54

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('group_number', models.IntegerField()),
                ('academic_subject', models.CharField(max_length=80)),
                ('date_of_creation', models.DateField(
                    default=datetime.date.today)),
                ('number_of_students', models.IntegerField(default=0)),
            ],
        ),
    ]
