# Generated by Django 3.2.4 on 2021-06-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_rename_groups_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='number_of_students',
            field=models.IntegerField(default=1),
        ),
    ]
