# Generated by Django 3.2.4 on 2021-07-08 06:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_number_of_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='update_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='number_of_students',
            field=models.IntegerField(default=0),
        ),
    ]
