# Generated by Django 3.2.4 on 2021-07-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20210708_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
