# Generated by Django 3.2.4 on 2021-07-12 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('groups', '0006_group_headman'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_group', to='courses.course'),
        ),
    ]
